_includes/sample.html

Like mentioned in ktorio/ktor#243, this should fix the link to the correct branch on github.

fix link to github (now master instead of develop)

---

pages/quickstart/application.md

Fixed the link from [Quick Start / Application](http://ktor.io/quickstart/application.html) to the [Artifacts](http://ktor.io/artifacts) page.
Removed the redundant trailing space (on the affected line only) along the way.

Fix link to the Artifacts page

---

pages/features/authentication-jwt.md

Should I include it in the already-existing-but-empty Authentication page, or should it have its own?

Added authentication-jwt feature

---

advanced/pipeline/route.md

Fixes a small typo in the document for calling the user provided route handler

Fix typo in doc for Route pipeline

---

clients/http-client/features/json-feature.md

I will update this example once i manage to make a common module for kotlinx-serialization work and get it merged
my other PR here: https://github.com/ktorio/ktor/pull/575
does not change anything in this example (except it will work out of the box with @Serializable annotated classes)

Update json-feature.md - add kotlinx-serialization section

---

kotlinx/io/tools.md

A few twisted letters and wrong constructs in the description text.

Fix ObjectPool example description spelling

---

quickstart/guides/chat.md

`Assigning names to users/connections` changed `wsConnections` -> `clients`

Fixed chat.md code block

---

advanced/0index.md
advanced/authentication.md
advanced/build-from-source.md
advanced/engines.md
advanced/events.md
advanced/features.md
advanced/http2.md
advanced/pipeline.md
advanced/pipeline/attributes.md
advanced/pipeline/route.md
advanced/utilities.md

This PR fixes grammar, word choice, punctuation, spelling errors, etc. in the "Advanced" section. I'm a native English speaker (US) and have a Bachelor of Arts in English. I didn't change any code in multiple lines enclosed by triple backticks. If anything wasn't clear to me, I researched it in the Ktor source code.
I'd planned to submit a single PR for all six sections (Quick Start, Servers, Clients, Kotlinx, Samples, Advanced), but since I have some questions, I decided to stop at Advanced and ask them. Once they are answered, I can make necessary changes to this PR and submit a new one for the other five sections.
If you like, I can submit a separate PR for each section. It might be easier for you to review.
Should I continue to use the rules outlined below? The Advanced section was …

Polish English in Advanced section

---

servers/features/status-pages.md

Some of the typos are related to official style-guide, but others will not allow the code to compile.

Fix typos in sample code for StatusPages

---

clients/3http-client.md
clients/http-client/calls/requests.md

`HttpClient`s should be closed once they have done their work, as demonstrated in the example [here](https://ktor.io/clients/http-client/examples.html#example-json). Otherwise a (ktor) server cannot gracefully stop without polluting logs with exceptions.
I added calls to the `client.close()` method to some samples and also wrote a small paragraph about it on the Requests page.

 Add client closing to sample code and requests description

---

quickstart/1index.md

There was a wrong link which led to Gradle Quick Start page.

Fix path to IntelliJ Plugin setup page

---

servers/features/authentication/oauth.md

Name `oauth1` is easy to confuse with OAuth 1.0, especially when passed as positional (not named) argument.

Meaningful name for auth

---

servers/features/authentication/oauth.md

`providerLookup` has type of `ApplicationCall.() -> OAuthServerSettings?` and, when implemented by lambda, has no inferred `it` parameter, so the original code won't compile.

Fixed providerLookup (by copy-pasting from sample)

---

servers/logging.md

It was not clear that putting the logback.xml without installing the Call Logging feature will not log requests. This small PR add a note on this topic.

Update logging.md to clarify Call Logging

---

quickstart/guides/4oauth.md

Fix tiny typo in quickstart/guides/4oauth.md

---

clients/http-client/9features.md

Links pointing to custom features in client documentation needs to be updated. Thanks

Fix borken links in 9features.md

---

servers/features/routing.md

Since the documentation does not describe if `higher priority == higher quality` or `lower priority == higher quality`, be consistent and just use "lower quality".

Clarify terms Accept header priority

---

quickstart/guides/1website.md

1. The path is changed to the correct path, that used on the screenshot
2. Changed the margins
3. Added `routing {}` and missed argument for `call.sessions.set`
4. Delete odd round bracket

Fix some typos in quickstart documentation

---

clients/http-client/calls/requests.md

`MultiPartFormDataContent` should be used with the `formData { ... }` DSL used in the example.

Update multipart/form-data example to use MultiPartFormDataContent

---

servers/features/authentication/oauth.md

The following line raises an error because the "type" properties is a string but loginProviders is a list:
```kotlin
providerLookup = { loginProviders[application.locations.resolve<LoginLocation>(LoginLocation::class, this).type] }
```
Is it possible that this example doesn't work? I added `.associateBy {it.name}` to the loginProviders and now it works for me.

Fix sample code in OAuth server documentation

---

servers/features/forward-headers.md

Change to `val remoteHost = request.origin.remoteHost`

Fix `val remoteHost = request.origin.method`

---

servers/0intro.md

The methode route{} was misspelled in 0intro.md

Correcting a misspelling in 0intro.md

---

clients/2websockets.md

Seems that older versions of ktor's websocket (like 1.1.4) has the name
`ktor-client-websocket`
and newer versions (like 1.2.x) use the name
`ktor-client-websockets`

Update library path for `ktor-client-websockets`

---

clients/http-client/2multiplatform.md

At the moment, multiplatform page might be a bit confusing since all platforms are explicitly explained, except for JVM (which has its own page).
This adds explicit mention and redirect to the JVM engine list.

Explicitly mention how to use multiplatform Ktor on JVM

---

servers/features/templates/freemarker.md

This fixes an unresolved reference error in 
`templateLoader = ClassTemplateLoader(TheApp::class.java.classLoader, "templates")`
TheApp is unknown and changing it to this fixes the error and FreeMarker feature is successfully installed.

Change parameter TheApp to this

---

clients/http-client/features/json-feature.md

Adds previously missing info about using `ktor-client-json-js` to the docs.

Include information about K/JS usage for ktor-client-json

---

servers/autoreload.md

Using `gradle -t build` tests (and lints) the program, which is unnecessary during development. It is unnecessary to run tests during the first run when automatic reload is enabled, since the program will continuously be fluctuating in terms of tests passing while being worked on. Linting is pointless for obvious reasons in this stage.
I was initially using the `assemble` task in place of `build` precisely for these same reasons, but the performance hit while using a bind mount in a Docker container was still far too severe. After some digging, I found that `assemble` compresses distributions (which takes roughly half the task's time), as well as runs the shadow tasks if the Shadow JAR plugin is present (which takes roughly half the task's time).
Since it took me quite a long time to fix …

Fix performance issue in autoreload.md

---

_includes/artifact.html

List artifacts individually and use 'testImplementation' ('testCompile' is deprecated).
Current issue:

Fix display of test artifacts in Gradle Kotlin DSL

---

servers/features/authentication/digest.md

When I've copy-pasted sample code, there was no suitable `digest` method.
So I've copied almost original `userNameRealmPasswordDigestProvider` implementation, but removed ISO charset so password can contain, for instance, cyrillic characters.

Fixed `userNameRealmPasswordDigestProvider`

---

servers/features/metrics-micrometer.md

The class MicrometerMetrics is in the package io.ktor.metrics.micrometer (see [https://github.com/ktorio/ktor/blob/master/ktor-features/ktor-metrics-micrometer/jvm/src/io/ktor/metrics/micrometer/MicrometerMetrics.kt](the source code)), so the class name at the top of this page is incorrect.

Small typo: Correct class name for MicrometerMetrics

---

_includes/artifact.html

I've noticed that [this page](https://ktor.io/clients/websockets.html) in the documentation correctly lists all Gradle dependencies, but Maven dependencies tab is wrong, because the first dependency is repeated there.
This should fix it.

Fix Maven tab in Artifact screen to correctly list all dependencies

---

servers/features/authentication/jwt.md

The example code in the JWT documentation had an error and was missing a crucial function. I fixed the error added the function present in [the sample](https://github.com/ktorio/ktor-samples/blob/master/feature/auth/src/io/ktor/samples/auth/JwtApplication.kt)

Fixed JWT documentation exemple code

---

servers/features/templates/freemarker.md
servers/features/templates/mustache.md
servers/features/templates/pebble.md
servers/features/templates/thymeleaf.md
servers/features/templates/velocity.md

first i saw that the mustache and pebble example didn't render the double curly braces `{{`, so this required a `{% raw %}` and `{% endraw %}` encapsulation (i hope).
i also made the samples more self-contained by adding the `User` data class definition.
also aligned all the template samples (except the html-dsl as it is somehow completely different than the rest), using same filename, render same output...

improve and align template samples

---

_layouts/home.html

You should directly link to YouTrack issues, instead linking to GitHub.

Move GitHub Issues to YouTrack Issues

---

servers/self-signed-certificate.md

Affected page: https://ktor.io/servers/self-signed-certificate.html
The `Using a Self-Signed Certificate` guide references an incorrect dependency - the `generateCertificate` function mentioned appears to have been moved to `io.ktor:ktor-network-tls-certificates`, from `io.ktor:ktor-network-tls`.
The rest of the guide seems OK for me locally.

Generation of self-signed certificates requires `io.ktor:ktor-network-tls-certificates`
