ktorio/ktorio.github.io

pages/servers/application.md

https://github.com/ktorio/ktor/issues/267

Minor grammatical fix to application page.

---

pages/servers/engine.md

Fix broken link in engine.md

---

features/webjars.md

Documentation associated with PR: https://github.com/ktorio/ktor/pull/498

Added webjars feature section

---

servers/calls/responses.md

It should be about response instead of request

Fix HTTP Status Code section

---

servers/uploads.md

Renamed the parameters for copying the file contents in the code example in the upload tutorial.

Renamed parameters in file upload code

---

quickstart/1index.md

Fixed a small typo in a heading

Fix typo in heading

---

quickstart/quickstart/docker.md

ktor-docker-sample-application -> my-application

Fix docker.md

---

servers/deploy/packing/0fatjar.md

Added a link to Shadow's docs.
Added what you need to add to `build.gradle` in order to actually generate the JAR.

Fat JAR with Shadow clarifications

---

servers/features/static-content.md

Fix typo in the doc

---

servers/testing.md

Removed an extra backtick and moved to a new line a code snippet

A couple of small fixes in testing.md

---

servers/features/cors.md

Add `exposeHeader()` and `exposeXHttpMethodOverride()` item

Add more configuration functions for CORS

---

servers/lifecycle.md

Fix broken links in lifecycle.md

---

servers/self-signed-certificate.md

Added missing import statement for `generateCertificate`
Removed unused imports

Fixed and optimized imports

---

quickstart/1index.md

Improvements on /quickstart/1index.md

---

servers/raw-sockets.md

Update the docs to remove references to ioCoroutineDispatcher and point to Dispatchers.IO instead.

Sockets; ioCoroutineDispatcher => Dispatchers.IO

---

servers/features/websockets.md

ReceiveChannel#consumeEach is deprecated and avoid `while(true){` for clean code sake

Use suspended iteration

---

servers/features/templates/thymeleaf.md

Add the document of Thymeleaf template.

Add Thymeleaf document

---

servers/features/metrics-micrometer.md
servers/features/metrics.md

Documentation for https://github.com/ktorio/ktor/pull/1037

Documented new micrometer feature

---

servers/testing.md

the existing description has a typo and could be a bit improved IMO

fix description of formUrlEncode

---

servers/features/sessions/transformers.md

https://github.com/ktorio/ktor/commit/43b8efeb6d1bf568359212afb3f862532cff3976

Default algorithm changed

---

servers/testing.md

Fixed a missing conversion in the example-code that prevented it from compiling

Make the example compile

---

servers/uploads.md

Use Dispatchers.IO rather than ioCoroutineDispatcher

Updated Upload to use Dispatchers correctly

---

clients/http-client/features/json-feature.md

See https://github.com/Kotlin/kotlinx.serialization/issues/516

Document Kotlinx.Serialization for iOS

---

servers/deploy/hosting/heroku.md

In addition i fixed the environment-variables href

Added a deployment error (stage task) solution

---

servers/0intro.md

Just a few grammatical tweaks to make this page easier to understand.

Grammatical changes to 0intro.md

---

servers/features/cors.md

Added updated path to tests

---

servers/testing.md

Fix the example so it compiles (given the right imports) and the test passes.

Fix "example with dependencies"

---

servers/configuration.md

...which seem to have been added in 1.2.0

Document the existence of ktor.deployment.rootPath

---

clients/http-client/features/http-cookies.md

Took me 20 minutes to understand why the hell I can't import the class...

Fixed typo in http-cookies.md

---

servers/features/templates/pebble.md

Documentation for ktorio/ktor#1374

Document Pebble Templating feature

---

quickstart/migration/1.4.0.md

Fix [KTOR-931](https://youtrack.jetbrains.com/issue/KTOR-931)

Add 1.4.0 migration guide.

---

quickstart/migration/1.4.0.md

Fix problems in 1.4.0 migration guide
